language: python
python:
  - "3.5"
dist: trusty
sudo: required
env:
  global:
    - SOLC_VERSION="0.4.8"
    - SOLC_BINARY_PATH="$TRAVIS_BUILD_DIR/solc-versions/bin-$SOLC_VERSION"
    - SOLC_BINARY="$SOLC_BINARY_PATH/solc"
    - LD_LIBRARY_PATH="$SOLC_BINARY_PATH"
  matrix:
    - TEST_DIR=block-scheduling
#    - TEST_DIR=timestamp-scheduling
#    - TEST_DIR=request-factory
#    - TEST_DIR=request-tracker
#    - TEST_DIR=transaction-request
cache:
  - pip: true
  - directories:
    - $HOME/.ethash
    - $TRAVIS_BUILD_DIR/solc-versions/binary-$SOLC_VERSION/
    - $TRAVIS_BUILD_DIR/solc-versions/source-$SOLC_VERSION/
before_install:
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update
install:
  - echo "DEBUG cache tree:" && find $TRAVIS_BUILD_DIR/solc-versions/ -exec file {} \;
  - ./bin/install_solc.sh
  - travis_retry sudo apt-get install -y ethereum
  - travis_retry pip install setuptools --upgrade
  - pip install -r requirements.txt
  - python setup.py install
before_script:
  - $SOLC_BINARY --version
  - mkdir -p $HOME/.ethash
  - geth makedag 0 $HOME/.ethash
script:
  - py.test tests/$TEST_DIR -v
