language: python
python:
  - "3.5"
dist: trusty
sudo: required
env:
  global:
    - SOLC_VERSION="0.4.6"
    - SOLC_BINARY="$TRAVIS_BUILD_DIR/solc-versions/solc-$SOLC_VERSION/solc"
  matrix:
    - TEST_DIR=block-scheduling
    - TEST_DIR=timestamp-scheduling
    - TEST_DIR=request-factory
    - TEST_DIR=request-tracker
    - TEST_DIR=transaction-request
cache:
  - pip: true
  - directories:
    - $HOME/.ethash
    - $TRAVIS_BUILD_DIR/solc-versions/solc-$SOLC_VERSION/
    - $TRAVIS_BUILD_DIR/solc-versions/solidity-$SOLC_VERSION/scripts/
    - $TRAVIS_BUILD_DIR/solc-versions/solidity-$SOLC_VERSION/build/
before_install:
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update
install:
  - ./bin/install_solc.sh
  - travis_retry sudo apt-get install -y ethereum
  - travis_retry pip install setuptools --upgrade
  - pip install -r requirements.txt
  - python setup.py install
before_script:
  - find $TRAVIS_BUILD_DIR/solc-versions/ -exec file {} \;
  - ./solc-versions/solc-$SOLC_VERSION/solc --version
  - mkdir -p $HOME/.ethash
  - geth makedag 0 $HOME/.ethash
script:
  - py.test tests/$TEST_DIR -v
